version: '3'

services:
  vk-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - 15352:15352
    environment:
      - PORT=${PORT}
      - VK_KEY=${VK_KEY}
      - APP_ID=${APP_ID}
    tty: true
    command: ["npm", "run", "dev"] 
