version: '3'

services:
  vk-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
      - ./db:${DB_PATH}
    ports: 
      - 15352:15352
    environment:
      - PORT=5000
      - VK_KEY=${VK_KEY}
      - APP_ID=${APP_ID}
      - BASE_PATH=""
      - DB_PATH=${DB_PATH}
    tty: true
    command: ["npm", "run", "dev"] 
