version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        BASE_PATH: ${BASE_PATH}
        APP_ID: ${APP_ID}
    volumes:
      - ./db:${DB_PATH}
    ports: 
      - ${EXPOSED_PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - VK_KEY=${VK_KEY}
      - DB_PATH=${DB_PATH}
    tty: true
